import type { Metadata } from 'next'
import { Inter, Lexend } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Player from '@/components/Player'

const inter = Inter({ subsets: ['latin'] })
const lexend = Lexend({
  subsets: ['latin'],
  weight: ['500', '600'],
  variable: '--font-lexend',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt">
      <body
        className={`${inter.className} ${lexend.variable} flex bg-pod-gray-50 antialiased`}
      >
        <main className="flex-1">
          <Header />
          {children}
        </main>
        <Player />
      </body>
    </html>
  )
}
